### ISSUE TITLE
Context menu are misplaced in Nautilus + Wayland

### ISSUE THREAD

**Issue by luca-viggiani** [Selenium-H/Animation-Tweaks#1]
Hi, on Nautilus 3.32 + Wayland, context menus on files / folders always appear at the top left of the screen.

**Comment by Selenium-H** [comment]
Hi @luca-viggiani , Although the extension does not work properly in wayland. The above issue can be fixed by enabling the "Use workaround for wayland" option  which is present in "About" tab in extension preferences. Have you tried that ?

**Comment by luca-viggiani** [comment]
Hi thanks for the answer. No I didn't even see that option, sorry. Ok I've tried and it works thanks.
As a suggestion, maybe the "About" section is not the best place for that option... I mean, it's not the place where an user would look. Perhaps an additional tab named "Advanced" would be more intuitive... Don't you think?
