### ISSUE TITLE
Application Window animations does not work in Manjaro (gnome 3.34.2)

### ISSUE THREAD

**Issue by tnilzon** [Selenium-H/Animation-Tweaks#12]
Application Window animations does not work in Manjaro Arch based). Other animations seem to work (i.e. popup menu).

System:
Kernel: 5.3.15-1-MANJARO x86_64 bits: 64 compiler: gcc
v: 9.2.0 Desktop: Gnome 3.34.1 wm: gnome-shell dm: GDM 3.34.1 
Distro: Manjaro Linux
Topology: Dual Core model: Intel Core i5-5257U bits: 64 type: MT MCP 
arch: Broadwell rev: 4 L2 cache: 3072 KiB

Animation-Tweaks Master (2019 December 12)

For me this is one of the "must have" extensions. So I am hoping this will be fixed, thanks.

**Comment by Selenium-H** [comment]
Fixed in Version 9.
