### ISSUE TITLE
The just released v9 has issues

### ISSUE THREAD

**Issue by tnilzon** [Selenium-H/Animation-Tweaks#13]
I have just tried the just released v9. It breaks gnome animation "restore" from maximized for some applications (this animation is in original already in gnome). If for example the Terminal window is maximized (with Window maximize button) and then restored (with Window restore button), the Terminal window is not restored (it "jerks" and stays maximized).

Animation-Tweaks v9
Manjaro gnome 3.34.2

**Comment by Selenium-H** [comment]
This extension does not handle maximize and restore animations. Please try completely removing and reinstalling this extension. Then resetting it ( Reset Button is present in extension preferences -> About tab ). Then restarting the gnome shell.

**Comment by tnilzon** [comment]
OK, thanks. I'll guess I was a bit to hasty to file this issue, sorry.

**Comment by Selenium-H** [comment]
No problem
