### ISSUE TITLE
Notification and OSD Animation

### ISSUE THREAD

**Issue by fdinardo** [Selenium-H/Animation-Tweaks#2]
Hi, 
Thanks for this extension.

I am wondering if there is a way to edit the notification (like a new message received) and the OSD notification (like volume up/down) animations

Thanks

**Comment by Selenium-H** [comment]
Hi @fdinardo , I can't find any ways to edit them.

**Comment by JasonLG1979** [comment]
> I am wondering if there is a way to edit the notification (like a new message received) and the OSD notification (like volume up/down) animations

You could monkey patch the method that sends the notification and change it to whatever you want.

Basically:

```js
const originalMethod = stuff.moreStuff.WhatEverMethod;

function enable() {
    // maybe do stuff?
    stuff.moreStuff.WhatEverMethod = monkeyPatch;
    // maybe do more stuff?
}

function disable() {
    // maybe do stuff?
    stuff.moreStuff.WhatEverMethod = originalMethod;
    // maybe do more stuff?   
}

function monkeyPatch(randomArg) {
    // Alter functionality.
    // may be even?
   // originalMethod(randomArg);
}
```

If the methods that handle the messages are signal handlers (they probably are) you can just disconnect the default handler and connect your own. Even if there's not a reference to the handler id you can find it with a combination of ```GObject.signal_parse_name``` and ``` GObject.signal_handler_find```. so you can disconnect the stock handler.

**Comment by Selenium-H** [comment]
Thanks @JasonLG1979  for explaining the process.

Notification and OSD animations are now implemented in [new-version](https://github.com/Selenium-H/Animation-Tweaks/tree/new-version)  branch.

**Comment by fdinardo** [comment]
Hi, when this will be pushed to the extension website?

**Comment by Selenium-H** [comment]
@fdinardo, Sorry for the delay. I'll upload once version 10 is done. ( shortly ).
