### ISSUE TITLE
Windows 10 like animations

### ISSUE THREAD

**Issue by ghost** [Selenium-H/Animation-Tweaks#21]
With the current update breaking basically everything every next update, is there a way to just have a fixed Windows 10 like animation system? My automation script to replicate the Windows 10 feel on the Linux Desktop keeps breaking because my config gets outdated with every next update of this tweak. If not, any recommendation for the same? Do I soft fork the Version 9.0 branch and link my script to the same?

**Comment by Selenium-H** [comment]
> With the current update breaking basically everything every next update, is there a way to just have a fixed Windows 10 like animation system?

I'll try including a `Restore Previous Settings` or any similar option if possible.

Also, you may write automation script as per `Version-9` or `Version-9.1` branch. They won't be updated anymore.

**Comment by ghost** [comment]
Thanks a lot. I will do the needful changes
