### ISSUE TITLE
Animation extension disabled when opening the terminal and always need a restart

### ISSUE THREAD

**Issue by Xanaxus** [Selenium-H/Animation-Tweaks#28]

**Comment by Selenium-H** [comment]
Sorry for the delay. Are there any messages in log ? Which version of GNOME Shell is it happening ?

**Comment by Xanaxus** [comment]
Hey no problem I not sure what was the issue but after reinstalling and then changing the shortcut it got fixed

As I realised the shortcut for my terminal and the shortcut cut for disabbling was the same and it had not registered the change in shortcut I guess but it works fine now
