### ISSUE TITLE
Support for Gnome 3.38

### ISSUE THREAD

**Issue by much-doge** [Selenium-H/Animation-Tweaks#30]
Gnome 3.38 has recently landed on rolling/bleeding edge distro such as Debian Sid.

**Comment by mrmelon54** [comment]
Here is the error I get on 3.38.0
```
Oct 03 21:43:38 m21 gnome-shell[2370]: JS ERROR: Extension animation-tweaks@Selenium-H: ImportError: No JS module 'tweener' found in search path
                                       @/home/sean/.local/share/gnome-shell/extensions/animation-tweaks@Selenium-H/extension.js:18:21
                                       _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:420:13
                                       loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:345:27
                                       _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:586:18
                                       collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
                                       _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:565:19
                                       _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:595:18
                                       _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:626:18
                                       init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
                                       _initializeUI@resource:///org/gnome/shell/ui/main.js:269:22
                                       start@resource:///org/gnome/shell/ui/main.js:159:5
                                       @<main>:1:47
```

**Comment by dlyr** [comment]
I think it's because tweener animation has been [replaced by clutter](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1200) animation in gnome 3.38
I'm not aware of the work of such an update, but I miss animation tweak !
Thanks if you can check and update your extension.

**Comment by mrmelon54** [comment]
Is there anyway I can force my laptop to downgrade to 3.37 and stay there?

**Comment by Selenium-H** [comment]
Last commit in [experimental](https://github.com/Selenium-H/Animation-Tweaks/tree/experimental) branch added GNOME Shell 3.38 support.

**Comment by dlyr** [comment]
@MrMelon54 to downgrade, google search should give help and example, for instance https://www.linuxuprising.com/2019/02/how-to-downgrade-packages-to-specific.html

**Comment by mrmelon54** [comment]
> Last commit in [experimental](https://github.com/Selenium-H/Animation-Tweaks/tree/experimental) branch added GNOME Shell 3.38 support.

I think I'll try installing from the experimental branch as gnome doesn't seem to list 3.37 only stable (3.30) and unstable (3.38)

**Comment by dlyr** [comment]
experimental branch works for me

**Comment by mrmelon54** [comment]
Lets hope some of the other extensions I use have a 3.38 version now or I might try and edit them and leave a PR. Only problem is I don't know much about making extensions for gnome shell

**Comment by mrmelon54** [comment]
Experimental works fine for me too
