### ISSUE TITLE
Option to change position of notifications

### ISSUE THREAD

**Issue by HritwikSinghal** [Selenium-H/Animation-Tweaks#34]
If you could add an option to shift notifications vertically and horizontally to any position on screen it would be great. (just like https://extensions.gnome.org/extension/708/panel-osd/) the default position is too much at top which covers close button

**Comment by Selenium-H** [comment]
Hi @HritwikSinghal, The vertical positions of the notification banner can be customized. Please try setting the `Movement Along Y` parameters to the desired value in `Customize Animation` window. A value of `0` means all the way to top and `100` means at the bottom of the screen. 


![Customize](https://user-images.githubusercontent.com/46006930/96260684-f904df80-0fdc-11eb-8b92-312c405dc8a4.gif)


The `Tween Parameters - "First Number"` denotes the position of the notification banner at the start of the animation and `Tween Parameters - "Last Number"` denotes the ending position of the notification banner.

**Comment by HritwikSinghal** [comment]
thank you! 
you should also mention this on the main readme since for beginners, its hard to find this setting in all those options (i tried tinkering with some of those options but couldn't find any soln till now)
