### ISSUE TITLE
Profiles for extension windows

### ISSUE THREAD

**Issue by somepaulo** [Selenium-H/Animation-Tweaks#36]
Is there a way of adding a profile for windows created by a specific GS extension?

I'm using ddterm (https://extensions.gnome.org/extension/3780/ddterm/ & https://github.com/amezin/gnome-shell-extension-ddterm) for a drop down terminal and I'd like to change its open/close animation to actually slide down on open and back up on close instead of Gnome's default window open animation. I don't know which type of window it is, and anyway, I would like to change only this extension's animation, not the whole class. I tried the Profiles option, but see no way of adding an extension there. So I guess this is a feature request since I didn't find a way to target that particular window.

I opened an [issue](https://github.com/amezin/gnome-shell-extension-ddterm/issues/16) with the ddterm developer, but he says he doesn't want to hack GS and sees no native way of changing the animation, So I was hoping your extension might help.

**Comment by Selenium-H** [comment]
The extension can animate windows created by GS extensions. However, currently there's no way to add them using extension preferences.

For `ddterm` extension.

Create a `ddterm.desktop` file in `~/.local/share/applications` folder and add the following lines.

```[Desktop Entry]
Name=Com.github.amezin.ddterm
Type=Application
Icon=utilities-terminal
NoDisplay=true
```
This will add `Com.github.amezin.ddterm` entry in application dialog box.

Open `Animation Tweaks` extension preferences and in `Profiles` -> `Application profiles` and add `Com.github.amezin.ddterm` to the list from application dialog box.

![ddterm](https://user-images.githubusercontent.com/46006930/99182412-d9d3ac00-275a-11eb-94f1-97f5ec6b7caa.png)

Set animations and enable `Application Profiles` Switch.

This will add `ddterm` extension window to profile and manage it properly.

**Comment by somepaulo** [comment]
Thank you!
Had to add `[Desktop Entry]` on top of the ddterm.desktop file, because I was getting errors saying that the _'key file didn't start with a group'_, and it wouldn't appear in the list of apps in Profiles settings.
Strangely, it only affects the opening animation, while the closing one remains Gnome's default no matter what I choose in Animation Tweaks profile settings (see attached screengrab).
![ddterm](https://user-images.githubusercontent.com/15643750/99189237-49549600-2771-11eb-9a45-90d2803b05b4.gif)
Nevermind the glitches in the gif, they're screen grabber related.

**Comment by Selenium-H** [comment]
> Had to add `[Desktop Entry]` on top of the ddterm.desktop file, because I was getting errors saying that the _'key file didn't start with a group'_, and it wouldn't appear in the list of apps in Profiles settings.

Yes. Sorry about that. 

I think `Closing Effects [ for Windows ]` switch is not enabled. Please enable it from `preferences` -> `Actions` -> `Close` -> `Closing Effects [ for Windows ]`.

If its enabled, try disabling and re-enabling the extension.

**Comment by somepaulo** [comment]
Yes!
Closing Effects were disabled by default. Enabling them fixed the issue straight away with no reloads or restarts.
Thank you!

**Comment by amezin** [comment]
Doesn't work on Wayland :(
