### ISSUE TITLE
New full screen window has gap on top

### ISSUE THREAD

**Issue by HritwikSinghal** [Selenium-H/Animation-Tweaks#37]
When we open a full screen window of any app, there is a big gap on top of window title bar and top screen end. 
![image](https://user-images.githubusercontent.com/29531474/103926810-7608a680-513f-11eb-8309-4e6d047a30b7.png)

This happens only when the opening effects for normal window are enabled (when opening effects for normal window are turned off, this issue is gone). Also this issue is there is this latest version 12 only, before that i didn't have this issue. 

On Ubuntu 20.04.1 clean install. (also happened on ubuntu 20.10)

And i am using dash to panel so i have removed my top bar.

**Comment by Selenium-H** [comment]
Fixed with last commit in [master](https://github.com/Selenium-H/Animation-Tweaks/tree/master) branch.

**Comment by HritwikSinghal** [comment]
new windows have gap on top and left side in version 14. On manjaro 21 gnome 3.38. @Selenium-H i have attached SS . However this gap is just showing the changed positions of buttons, the actual position of buttons is same as that without gap.
so if i click above a button, it will perform that action.

![Screenshot from 2021-06-26 22-41-59](https://user-images.githubusercontent.com/29531474/123520761-eb593b00-d6cf-11eb-9347-3d94d54bcacc.png)

**Comment by HritwikSinghal** [comment]
> new windows have gap on top and left side in version 14. On manjaro 21 gnome 3.38. @Selenium-H i have attached SS . However this gap is just showing the changed positions of buttons, the actual position of buttons is same as that without gap.
> so if i click above a button, it will perform that action.
> 
> ![Screenshot from 2021-06-26 22-41-59](https://user-images.githubusercontent.com/29531474/123520761-eb593b00-d6cf-11eb-9347-3d94d54bcacc.png)

This is only with Matcha theme. It does not happen with Adaiwata or Yaru theme

**Comment by Selenium-H** [comment]
Fixed with the last commit in [master](https://github.com/Selenium-H/Animation-Tweaks/tree/master) `branch`.
