### ISSUE TITLE
profile options only work if global toogles are enabled

### ISSUE THREAD

**Issue by Optiligence** [Selenium-H/Animation-Tweaks#38]
I have to enable Open → Opening Effects [ for windows ] for a profile option to take effect. 
The status toggles on the profile also don’t seem to change anything.

**Comment by Selenium-H** [comment]
Hi @Optiligence, the global toggles actually lets extension handle the `opening` (`closing, minimizing and unminimizing`) actions for all windows. The `Applications Profiles` option only tells the extension to use profiles and add any animation for a listed application so that, the extension uses that instead of the global `opening` (`closing, minimizing or unminimizing`) animations. The `status` toggle then overrides the global effect status for that application.

**Comment by Optiligence** [comment]
hm, i just not noticed that if you open the profile page for the first time after opening the settings, there is actually no profile selected
changing any of the options doesn’t do anything at that point?
the profile status toggles do seem to work now, so this was probably what happened

that the global toggles are required is just confusing the way it is now, imo
for better usability the profile rows could e.g. be greyed out if they are disabled…

to give some perspective: 
in the beginning i created a profile for one application, which didn’t seem to work
i eventually found that enabling the global status for open normal windows would actually do what i wanted it to (although it applied to all applications, then)
that didn’t work for the close animation though
i only noticed months later that those global toggles exist and that the profile actually works

i might have accidentally enabled the global open but not the close toggle at some point in the beginning, it may have been the default

i just think it’s not very intuitive

as i said the whole thing would be much easier to understand if all the controls were disabled when the global toggle is off
and that the global toggle is required for profiles is arguable, i guess

**Comment by Selenium-H** [comment]
> if you open the profile page for the first time after opening the settings, there is actually no profile selected
> changing any of the options doesn’t do anything at that point?

Yes

> that the global toggles are required is just confusing the way it is now, imo
> for better usability the profile rows could e.g. be greyed out if they are disabled…

Thanks for the suggestion. I'll try implementing it.

**Comment by Selenium-H** [comment]
Implemented in [experimental](https://github.com/Selenium-H/Animation-Tweaks/tree/experimental) branch. The Preferences UI now makes status button insensitive depending on the preferences.
