### ISSUE TITLE
[Feature Request] Gnome 40 compatibility

### ISSUE THREAD

**Issue by theol0403** [Selenium-H/Animation-Tweaks#40]
Not much needs to be said :p. I would love to try this extension with gnome 40!

Currently, the error "this.panelBoxSignalHandlers is undefined" is shown in the extensions app, and the settings menu is broken.

```
Error: No property margin on Gjs_PrefsWindowForOpening_AnimationTweaksExtension
```

Other than fixing the syntax issues, I don't know if anything else needs to be changed to maintain the functionality of this extension. 

Thanks!

Edit: Issue #40 is perfect :p

**Comment by Selenium-H** [comment]
Last commit in [Experimental](https://github.com/Selenium-H/Animation-Tweaks/tree/experimental) `branch` added GNOME Shell 40 support.
