### ISSUE TITLE
Animation time for minimize and unminimize is set to 10 ms

### ISSUE THREAD

**Issue by Shaurya-Kalia** [Selenium-H/Animation-Tweaks#42]
Under the Minimize/Unminimize tab, all times are set to 10 ms and keep resetting to it when changed. Tested on gnome 40.1.0 wayland in manjaro
![Screenshot from 2021-06-03 23-42-39](https://user-images.githubusercontent.com/6441797/120692797-e08efa00-c4c5-11eb-8dde-65703a84fb75.png)

**Comment by Selenium-H** [comment]
Last commit in [master](https://github.com/Selenium-H/Animation-Tweaks/tree/master) branch, `Version 13.01` fixed this issue. 

After installing (Log out and log in back for wayland), in the `Update` tab in `Preferences` window -
 
Please select `Reset Animation Tweaks Extension` if possible, to clear the preferences which eliminates this issue.  

If you select `Keep Preferences and Upgrade` option, Although the extension should work fine, some of the `Time` parameter may have this issue. In that case please do the following (for the time being)-
Click on the gear icon for that item to open `Customize Animation` window.
![Screenshot from 2021-06-04 15-06-55](https://user-images.githubusercontent.com/46006930/120781264-8a15d000-c546-11eb-99fe-0c2481036088.png)
Click on `Restore Default` button on top right. 
This resets the effect parameters and fixes this issue.
