### ISSUE TITLE
Setting for Open Dialog Windows not applied

### ISSUE THREAD

**Issue by auipga** [Selenium-H/Animation-Tweaks#45]
To reproduce:
- Set these settings:
  - Open | Dialog Windows: effect-a
  - Close | Dialog Windows: effect-b
  - Open | Modal Dialog: effect-c
  - Close | Modal Dialog: effect-d
- Disable all other effects (optional)

Result:
- Dialog Window opens with effect-**c ← wrong**
- Dialog Window opens with effect-b
- Modal Dialog opens with effect-c
- Modal Dialog opens with effect-d

**Comment by Selenium-H** [comment]
Thanks for the detailed description. Actually it's not an issue of the extension. animations are applied based on its window type. It depends on how the application sets the window type.  
For example - The `About Text Editor` Dialog for `Gedit` is a `Modal Dialog` while `About` Dialog for `GNOME Terminal` is a `Dialog` window.

**Comment by auipga** [comment]
**IF** a window doesn't change its type during its lifecycle, I assume that it will open AND close with the effects set for **that** same specific type.

ATM I can't reproduce as the Dialog Window effect is not applied at all.

**Comment by auipga** [comment]
I don't know anymore which Dialog Window behaved wrong.
PhpStorm's commit window (Dialog Window) opens and closes correctly.
Closing.
