### ISSUE TITLE
[Feature Request] Indicate unsaved changes and prevent data loss

### ISSUE THREAD

**Issue by auipga** [Selenium-H/Animation-Tweaks#48]
When a profile is changed the Save button turns enabled. I would like to see an asterisk append to the currently selected profile.

When I try to switch the current profile while there are unsaved changes: ask the user what to do: cancel, save, forget.

(no pressure: I do not use profiles... yet)

**Comment by Selenium-H** [comment]
Implemented with last commit in [experimental](https://github.com/Selenium-H/Animation-Tweaks/tree/experimental) `branch`
