### ISSUE TITLE
[Bug] Dropdown List of effects can't be scrolled

### ISSUE THREAD

**Issue by auipga** [Selenium-H/Animation-Tweaks#49]
The selectable list doesn't show all entries if the monitor doesn't provide enough space to the upside or downside.

![image](https://user-images.githubusercontent.com/876689/122770389-ae431200-d2a5-11eb-9334-ad489636ff17.png)

**Workaround**
I can select effects outside the shown range is to use arrow keys (while focus is on that field) 

**Another workaround** (better usability, but often leads to bad results)
I can use the scroll wheel while hovering it the desired item.
The bad thing is that scrolling can lead to scrolling the whole settings dialog (e.g. when I already selected the first or last option). The next scroll event is then fired to some different item effectively loosing some of my settings.

**Comment by Sultech** [comment]
can you please fix this I cant select the animations I need using gnome 40

**Comment by auipga** [comment]
@Sultech you can focus the dropdown (but keep it closed) and then use <kbd>Arrow-Up</kbd>/<kbd>Arrow-Down</kbd>. You can also use your scrollwheel while the dropdown is hovered. (Be careful! If the window doesn't fit all the elements and can therefore also be scrolled. You probably will mess up other entries.)

**Comment by Selenium-H** [comment]
Sorry for the delay. Last commit in [master](https://github.com/Selenium-H/Animation-Tweaks/tree/master) `branch` fixed this issue.
