### ISSUE TITLE
None of the animations are working properly

### ISSUE THREAD

**Issue by ruvaldak** [Selenium-H/Animation-Tweaks#54]
Can't seem to figure out why, but I've tried everything I can think of in my smooth lil brain. Instlaling from gnome extensions, installing from AUR, installing directly from github, restarting shell, rebooting PC, disabling all other extensions. None of the custom animations seem to want to to work at all. Changing duration doesn't seem to work at all either, it just resets to whatever was the default. Some animations even end up like this, if they they decide not working whatsoever isn't cool enough for them:

![image](https://user-images.githubusercontent.com/15901769/135703670-4fee0e26-0113-4038-aab6-8f928677dc3c.png)

I'm wondering if maybe I'm missing some dependencies?

**Comment by Selenium-H** [comment]
Is this happening only for `Opening` animations or none of the actions (`Closing`, `Minimize` etc.) also doesn't animate? Also could you please let me know the `GNOME` version? 

Also, please try installing from the [experimental](https://github.com/Selenium-H/Animation-Tweaks/tree/experimental) `branch`.

**Comment by ruvaldak** [comment]
> Is this happening only for `Opening` animations or none of the actions (`Closing`, `Minimize` etc.) also doesn't animate? Also could you please let me know the `GNOME` version?
> 
> Also, please try installing from the [experimental](https://github.com/Selenium-H/Animation-Tweaks/tree/experimental) `branch`.

Gnome version is... 40.4.0. Absolutely no animations work whatsoever that I've seen, and those that do are just broken. The ones that don't work just revert to default behavior, it seems.

I'll give experimental a try

**Comment by ruvaldak** [comment]
Seems experimental is working for me just fine
